export const TAGS = {
    a: 'a',
    button: 'button',
    div: 'div',
    footer: 'footer',
    form: 'form',
    h1: 'h1',
    h2: 'h2',
    header: 'header',
    img: 'img',
    input: 'input',
    label: 'label',
    main: 'main',
    option: 'option',
    p: 'p',
    select: 'select',
    span: 'span',
};

export const CLASSNAMES = {
    footer: [['footer__gh'], ['footer__year'], ['footer__portfolio']],
    defaultBg: ['default__bg'],
    welcomeSubTitleContainer: ['welcome__sub-title-container'],
    welcomeSubTitle: ['welcome__sub-title'],
    welcomeBtnsCont: ['welcome__btns-container'],
    loginMainTitle: ['login__main-title'],
    loginForm: ['login__form'],
    loginBtn: ['login__btn'],
    loginInputName: ['login-name'],
    loginInputSurname: ['login-surname'],
    gameSelectLevel: ['game__select-level'],
    gameSelectPage: ['game__select-page'],
    gameControl: ['game__control-container'],
    gameControlBtnsCont: ['game__control-btns-container'],
    gameControlBtnExit: ['game__control-btns-exit'],
    gameControlBtnHint: ['game__control-btns-hint'],
    gameControlBtnAud: ['game__control-btns-audio'],
    gameControlBtnPic: ['game__control-btns-picture'],
    gameFieldCont: ['game__field-container'],
    gameBtnsCont: ['game__btns-container'],
    gameBtnStats: ['game__btn-stats'],
    gameBtnPressed: ['btn-pressed'],
    gameExampleCont: ['game__example-cont'],
    gameExampleSoundBtn: ['game__example-btn'],
    gameExampleTitle: ['game__example-title'],
    gameExampleBlur: ['hidden'],
    gameFieldInputCont: ['game__field-input'],
    gameFieldInputItm: 'game__field-itm',
    gameFieldSentCounter: 'game__field-sent',
    gameFieldMainCont: ['game__field-main-container'],
    gameFieldMainValues: ['game__field-main-values-cont'],
    gameFieldMainLines: ['game__field-main-lines-cont'],
    gameFieldTempElement: ['game__field-temp-el'],
    gameStatusPassed: ['option-passed'],
    gameStatusPending: ['option-pending'],
    gameImgTitle: ['game__img-title'],
    gameCurrentSentValue: ['current-value'],
    modalStatsCont: ['modal__stats-container'],
    modalBg: ['modal__bg'],
    modalStatsInfoCont: ['modal__info-container'],
    modalStatsResCont: ['modal__results-container'],
    modalStatsResHeader: ['modal__results-header'],
    modalStatsResUnknown: ['modal__results-unknown'],
    modalStatsResKnown: ['modal__results-known'],
    modalStatsResStatus: ['unknown-count', 'known-count'],
    modalStatsResAudio: ['modal__results-audio'],
    modalStatsBtn: ['modal__btn'],
};

export const TEXTCONTENT = {
    headerTitle: 'ENGLISH PUZZLE',
    welcomeMainTitle: 'Welcome, my friend!',
    welcomeSubTitle: [
        '🧐 Click on words, collect phrases.',
        '🤏🏼 Words can be drag and drop. Select tooltips in the menu',
        '🧩 Learn English and discover new works of art',
        'Are you ready to enter the magical world of puzzles?',
    ],
    welcomeBtn: 'Start',
    welcomeLogout: 'Logout',
    loginMainTitle: 'Please login to continue',
    loginLabelName: 'Enter your name:',
    loginLabelSurname: 'Enter your surname:',
    loginInputName: 'Ivan',
    loginInputSurname: 'Ivanov',
    loginBtn: 'Login',
    gameSelectLevel: 'Level',
    gameSelectPage: 'Round',
    gameBtnIdk: "I don't know",
    gameBtnContinue: 'Next sentence',
    gameBtnStats: 'Results',
    gameBtnNextRound: 'Next round',
    gameBtnNextLevel: 'Next level',
    gameBtnCheck: 'Check',
    modalStatsBtn: 'Continue',
    modalStatsResStatus: ["I don't know", 'I know'],
    footer: ['By Pavel Terno', '2024', 'More works here:'],
};

export const INPUT_VALIDATION = {
    valueMissing: 'Before submit you need to write something',
    tooShort: 'Your name is too short',
    patternMismatch: 'Your name must begin with a capital letter and must contain only English letters or dashes',
};

export const COLORS = {
    defaultColor: 'black',
    itmsTempBg: '#73AE2C',
    itmsRight: '#A1F43D',
    itmsWrong: '#DB0058',
};

export const WAYS = {
    imgIntoGameField: 'assets/img',
};

export const FONTPROPS = {
    itmsFont: '13px Inter',
    hintSmallFont: '9px',
    hintMediumFont: '11px',
    hintBigFont: '15px',
};
